### PR TITLE
fix: Portal frontend 6

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/64)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/64)* status: all files reviewed, 2 unresolved discussions (waiting on @SKairinos)

___
*[`src/theme/palette.ts` line 14 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/64#-O8M1Q4L2ZpYZIcbdsVI:-O8M1Q4MCroToMSlhIwi:b27kxub) ([raw file](https://github.com/ocadotechnology/codeforlife-package-javascript/blob/2cc813f4cf87903f236197a868df2aec9bce2e75/src/theme/palette.ts#L14)):*
> ```XML
> declare module "@mui/material/styles" {
>   interface CustomPaletteColors {
>     tertiary: PaletteColor
> ```

Is this needed, is `tertiary` the same as `student`?
___
*[`src/theme/palette.ts` line 26 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/64#-O8M1Vfj-t2jv0DatGws:-O8M1Vfj-t2jv0DatGwt:b-80wp0l) ([raw file](https://github.com/ocadotechnology/codeforlife-package-javascript/blob/2cc813f4cf87903f236197a868df2aec9bce2e75/src/theme/palette.ts#L26)):*
> ```XML
> 
> export interface PropsColorOverrides {
>   tertiary: true
> ```

Same question

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/64)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[`src/theme/palette.ts` line 14 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/64#-O8M1Q4L2ZpYZIcbdsVI:-O8M3VisD8XNJ33ywQSj:b789lvu) ([raw file](https://github.com/ocadotechnology/codeforlife-package-javascript/blob/2cc813f4cf87903f236197a868df2aec9bce2e75/src/theme/palette.ts#L14)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Is this needed, is `tertiary` the same as `student`?
</blockquote></details>

Yes. MUI uses the design language primary, secondary, etc. (MUI needs this) MUI uses these color names since it's a framework. 

However, I gave the colors extra names tailored to our app to make it more dev friendly. Now we also have the "teacher" color, for example.

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/64)* status: all files reviewed, 2 unresolved discussions (waiting on @SKairinos)

___
*[`src/theme/palette.ts` line 14 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/64#-O8M1Q4L2ZpYZIcbdsVI:-O8MG856-K7b7kdOFqOD:bnowtou) ([raw file](https://github.com/ocadotechnology/codeforlife-package-javascript/blob/2cc813f4cf87903f236197a868df2aec9bce2e75/src/theme/palette.ts#L14)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

Yes. MUI uses the design language primary, secondary, etc. (MUI needs this) MUI uses these color names since it's a framework. 

However, I gave the colors extra names tailored to our app to make it more dev friendly. Now we also have the "teacher" color, for example.
</blockquote></details>

And how come primary and secondary aren't in there?

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/64)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[`src/theme/palette.ts` line 14 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/64#-O8M1Q4L2ZpYZIcbdsVI:-O8MPQM36UUkjminDJ07:b-rvwp6o) ([raw file](https://github.com/ocadotechnology/codeforlife-package-javascript/blob/2cc813f4cf87903f236197a868df2aec9bce2e75/src/theme/palette.ts#L14)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

And how come primary and secondary aren't in there?
</blockquote></details>

they are default values

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/64)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[`src/theme/palette.ts` line 14 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/64#-O8M1Q4L2ZpYZIcbdsVI:-O8MPfdVDHNkzcuoOtJI:b-8htp39) ([raw file](https://github.com/ocadotechnology/codeforlife-package-javascript/blob/2cc813f4cf87903f236197a868df2aec9bce2e75/src/theme/palette.ts#L14)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

they are default values
</blockquote></details>

https://docs.codeforlife.education/software-developer-guide/dev-environment-setup#macos

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/64)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[`src/theme/palette.ts` line 14 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/64#-O8M1Q4L2ZpYZIcbdsVI:-O8MPiMn83VBn68QpSOp:b-hz70fi) ([raw file](https://github.com/ocadotechnology/codeforlife-package-javascript/blob/2cc813f4cf87903f236197a868df2aec9bce2e75/src/theme/palette.ts#L14)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

https://docs.codeforlife.education/software-developer-guide/dev-environment-setup#macos
</blockquote></details>

meant to share this link
https://mui.com/material-ui/customization/palette/#default-colors

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/64#-:-O8MPvdJBECxAZCZKg6j:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
