### PR TITLE
fix: auth flow

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/43)

### CODE REVIEW

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/43)* status: 0 of 49 files reviewed, 1 unresolved discussion

___
*[`src/hooks/auth.tsx` line 22 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/43#-O-fkItt-EBYWQY9FuYw:-O-fkItt-EBYWQY9FuYx:bo2zyef) ([raw file](https://github.com/ocadotechnology/codeforlife-package-javascript/blob/f4e0106e5083a34b843065d76c8ad7c61175e170/src/hooks/auth.tsx#L22)):*
> ```XML
> }
> 
> export function useSessionRequired(
> ```

fix navigate path name

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 44 of 49 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/43)* status: 46 of 49 files reviewed, 4 unresolved discussions (waiting on @SKairinos)

___
*[`src/components/form/EmailField.tsx` line 22 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/43#-O-k42G15hidqkZ5rmgK:-O-k42G2DT-hyDyBPLmy:bxlqzxx) ([raw file](https://github.com/ocadotechnology/codeforlife-package-javascript/blob/d07d4b011f53b4497e9e85eb3d3820ddf3af1f99/src/components/form/EmailField.tsx#L22)):*
> ```XML
>       schema={YupString().email()}
>       name={name}
>       placeholder={placeholder}
> ```

Generic reminder to clarify our preference between placeholder vs label with Laura - we can still merge this in for now though
___
*[`src/components/form/OtpField.tsx` line 14 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/43#-O-k4IHm3jFrSmaNNg73:-O-k4IHm3jFrSmaNNg74:bf5kkxk) ([raw file](https://github.com/ocadotechnology/codeforlife-package-javascript/blob/d07d4b011f53b4497e9e85eb3d3820ddf3af1f99/src/components/form/OtpField.tsx#L14)):*
> ```XML
> const OtpField: FC<OtpFieldProps> = ({
>   name = "otp",
>   placeholder = "123456",
> ```

Food for thought: this makes me think that this is perhaps how we should approach this:

- label = "defines the field" eg. "OTP" in this case
- placeholder = "gives an example" eg. "123456"
- helper text = "helps in case of error" eg. "Must be exactly 6 digits".
___
*[`src/components/form/TextField.tsx` line 51 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/43#-O-k4z9hETXoaKQTTY-z:-O-k4z9hETXoaKQTTY0-:b58qb33) ([raw file](https://github.com/ocadotechnology/codeforlife-package-javascript/blob/d07d4b011f53b4497e9e85eb3d3820ddf3af1f99/src/components/form/TextField.tsx#L51)):*
> ```XML
>             onBlur={form.handleBlur}
>             error={error}
>             helperText={error ? (form.errors[name] as string) : helperText}
> ```

Cf my previous comment, we probably don't need this custom logic in the end if we decide to ensure helper text is used for errors only.

**Review by faucomte97 — COMMENTED** [review]
> Reviewed 2 of 49 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/43)* status: all files reviewed, 4 unresolved discussions (waiting on @SKairinos)

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/43)* status: 43 of 50 files reviewed, 3 unresolved discussions (waiting on @faucomte97)

___
*[`src/components/form/EmailField.tsx` line 22 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/43#-O-k42G15hidqkZ5rmgK:-O-kfKyi-VwerA15MWOu:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-javascript/blob/d07d4b011f53b4497e9e85eb3d3820ddf3af1f99/src/components/form/EmailField.tsx#L22)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Generic reminder to clarify our preference between placeholder vs label with Laura - we can still merge this in for now though
</blockquote></details>

Done.
___
*[`src/components/form/OtpField.tsx` line 14 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/43#-O-k4IHm3jFrSmaNNg73:-O-kfK137MXAR5Dvl6hp:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-javascript/blob/d07d4b011f53b4497e9e85eb3d3820ddf3af1f99/src/components/form/OtpField.tsx#L14)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Food for thought: this makes me think that this is perhaps how we should approach this:

- label = "defines the field" eg. "OTP" in this case
- placeholder = "gives an example" eg. "123456"
- helper text = "helps in case of error" eg. "Must be exactly 6 digits".
</blockquote></details>

Done.
___
*[`src/hooks/auth.tsx` line 22 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/43#-O-fkItt-EBYWQY9FuYw:-O-kfDL8C8F-Hy_0Zpw9:b-hpd8qr) ([raw file](https://github.com/ocadotechnology/codeforlife-package-javascript/blob/f4e0106e5083a34b843065d76c8ad7c61175e170/src/hooks/auth.tsx#L22)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

fix navigate path name
</blockquote></details>

Done. The navigate path is now dynamically determined by the user type.

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/43)* status: 43 of 50 files reviewed, 3 unresolved discussions (waiting on @faucomte97)

___
*[`src/components/form/TextField.tsx` line 51 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/43#-O-k4z9hETXoaKQTTY-z:-O-kfMcSEw9o1u6ssVo8:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-javascript/blob/d07d4b011f53b4497e9e85eb3d3820ddf3af1f99/src/components/form/TextField.tsx#L51)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Cf my previous comment, we probably don't need this custom logic in the end if we decide to ensure helper text is used for errors only.
</blockquote></details>

Done.

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/43#-:-O-kfiGs1CBoMdcQezqp:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
